Repository UBC-Thunderbots/Software, pull requests merged in 2019-02, with the labels that each got.

#273 Implemented MoveSpinPrimitive for grsim backend
  src/thunderbots/software/CMakeLists.txt
  src/thunderbots/software/grsim_communication/main.cpp
  src/thunderbots/software/grsim_communication/visitor/grsim_command_primitive_visitor.cpp
  src/thunderbots/software/test/grsim_command_primitive_visitor/move_spin_primitive.cpp
Labels: WIP

#313 Polygon support for visualizer messenger
  src/thunderbots/software/util/visualizer_messenger/visualizer_messenger.cpp
  src/thunderbots/software/util/visualizer_messenger/visualizer_messenger.h
Labels: P2 - medium

#361 Properly clearing layers fix
  src/thunderbots/software/util/visualizer_messenger/visualizer_messenger.cpp
Labels: P0 - urgent, T - bug

#335 (4/4) Implement MRF Backend
  src/thunderbots/software/launch/ai.launch
  src/thunderbots/software/launch/ai_grsim.launch
  src/thunderbots/software/launch/ai_mrf.launch
  src/thunderbots/software/radio_communication/main.cpp
  src/thunderbots/software/radio_communication/mrf/dongle.cpp
  src/thunderbots/software/radio_communication/mrf_backend.cpp
  src/thunderbots/software/radio_communication/mrf_backend.h
  src/thunderbots/software/util/parameter/dynamic_parameters.h
Labels: A - radio, WIP
