Repository UBC-Thunderbots/Software, pull requests merged in 2024-07, with the labels that each got.

#3234 Align with ball before attempting to dribble
  src/proto/parameters.proto
  src/shared/2021_robot_constants.cpp
  src/shared/constants.h
  src/software/ai/hl/stp/tactic/dribble/dribble_fsm.cpp
  src/software/ai/hl/stp/tactic/dribble/dribble_fsm.h
  src/software/ai/hl/stp/tactic/dribble/dribble_tactic_test.cpp
  src/software/world/robot.cpp
Labels: Gameplay

#3204 Fixed Replay Issues
  src/software/field_tests/field_test_fixture.py
  src/software/thunderscope/replay/BUILD
  src/software/thunderscope/replay/proto_logger.py
  src/software/thunderscope/replay/proto_player.py
  src/software/thunderscope/replay/replay_constants.py
  src/software/thunderscope/replay/replay_file_debugging_script.py
  src/software/thunderscope/replay/test/BUILD
  src/software/thunderscope/replay/test/replay_corruption_test.py
  src/tbots.py
Labels: Robocup-2024

#3230 [Gameplay] Avoid Aimless Kick/Chip by Defenders
  docs/fsm-diagrams.md
  src/proto/parameters.proto
  src/proto/tactic.proto
  src/software/ai/hl/stp/play/crease_defense/crease_defense_play_fsm.cpp
  src/software/ai/hl/stp/play/defense/defense_play_base.cpp
  src/software/ai/hl/stp/play/defense/defense_play_base.h
  src/software/ai/hl/stp/play/defense/defense_play_fsm.cpp
  src/software/ai/hl/stp/play/enemy_ball_placement/enemy_ball_placement_play_fsm.cpp
  src/software/ai/hl/stp/play/enemy_free_kick/enemy_free_kick_play_fsm.cpp
  src/software/ai/hl/stp/play/enemy_free_kick_play.cpp
  src/software/ai/hl/stp/play/free_kick_play.cpp
  src/software/ai/hl/stp/play/shoot_or_chip_play.cpp
  src/software/ai/hl/stp/play/stop_play.cpp
  src/software/ai/hl/stp/stp_tactic_assignment_test.cpp
  src/software/ai/hl/stp/tactic/crease_defender/BUILD
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_fsm.cpp
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_fsm.h
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_fsm_test.cpp
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_tactic.cpp
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_tactic.h
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_tactic_test.cpp
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_tactic_test.py
  src/software/ai/hl/stp/tactic/tactic_factory.cpp
  src/software/ai/motion_constraint/motion_constraint_set_builder_test.cpp
  src/software/simulated_tests/BUILD
  src/software/simulated_tests/ball_is_off_ground.py
Labels: Robocup-2024

#3207 Gamecontroller can Bind to a Different Port Based on Command Line Argument
  src/software/field_tests/field_test_fixture.py
  src/software/networking/ssl_proto_communication.py
  src/software/thunderscope/binary_context_managers/game_controller.py
  src/software/thunderscope/robot_communication.py
  src/software/thunderscope/thunderscope_main.py
Labels: Robocup-2024

#3225 Save Proto Log
  src/software/thunderscope/common/proto_configuration_widget.py
  src/software/thunderscope/constants.py
  src/software/thunderscope/widget_setup_functions.py
Labels: Robocup-2024

#3239 Rewrite ProtoLogger in C++
  src/proto/BUILD
  src/shared/constants.h
  src/shared/test_util/tbots_gtest_main.cpp
  src/software/backend/BUILD
  src/software/backend/unix_simulator_backend.cpp
  src/software/backend/unix_simulator_backend.h
  src/software/constants.h
  src/software/er_force_simulator_main.cpp
  src/software/field_tests/BUILD
  src/software/field_tests/field_test_fixture.py
  src/software/jetson_nano/services/robot_auto_test.cpp
  src/software/logger/BUILD
  src/software/logger/logger.h
  src/software/logger/proto_logger.cpp
  src/software/logger/proto_logger.h
  src/software/logger/protobuf_sink.cpp
  src/software/logger/protobuf_sink.h
  src/software/multithreading/BUILD
  src/software/multithreading/observer_subject_adapter_test.cpp
  src/software/multithreading/thread_safe_buffer.hpp
  src/software/networking/unix/BUILD
  src/software/networking/unix/proto_unix_listener.hpp
  src/software/networking/unix/threaded_proto_unix_listener.hpp
  src/software/networking/unix/threaded_proto_unix_sender.hpp
  src/software/py_constants.cpp
  src/software/python_bindings.cpp
  src/software/simulated_tests/BUILD
  src/software/simulated_tests/simulated_er_force_sim_test_fixture.cpp
  src/software/simulated_tests/simulated_test_fixture.py
  src/software/simulated_tests/tbots_test_runner.py
  src/software/thunderscope/BUILD
  src/software/thunderscope/binary_context_managers/full_system.py
  src/software/thunderscope/constants.py
  src/software/thunderscope/replay/BUILD
  src/software/thunderscope/replay/proto_logger.py
  src/software/thunderscope/replay/proto_player.py
  src/software/thunderscope/replay/replay_constants.py
  src/software/thunderscope/replay/replay_file_debugging_script.py
  src/software/thunderscope/replay/test/BUILD
  src/software/thunderscope/replay/test/replay_corruption_test.py
  src/software/thunderscope/thunderscope_main.py
  src/software/unix_full_system_main.cpp
Labels: Robocup-2024

#2953 Improve FreeKickPlay behaviour and convert it to use FSMs
  docs/fsm-diagrams.md
  docs/software-architecture-and-design.md
  src/proto/parameters.proto
  src/proto/play.proto
  src/shared/constants.h
  src/software/ai/hl/stp/play/BUILD
  src/software/ai/hl/stp/play/free_kick/BUILD
  src/software/ai/hl/stp/play/free_kick/free_kick_play.cpp
  src/software/ai/hl/stp/play/free_kick/free_kick_play.h
  src/software/ai/hl/stp/play/free_kick/free_kick_play_fsm.cpp
  src/software/ai/hl/stp/play/free_kick/free_kick_play_fsm.h
  src/software/ai/hl/stp/play/free_kick/free_kick_play_test.cpp
  src/software/ai/hl/stp/play/free_kick/free_kick_play_test.py
  src/software/ai/hl/stp/play/free_kick_play.cpp
  src/software/ai/hl/stp/play/free_kick_play.h
  src/software/ai/hl/stp/tactic/attacker/attacker_fsm.cpp
  src/software/ai/hl/stp/tactic/chip/chip_fsm.cpp
  src/software/ai/hl/stp/tactic/chip/chip_fsm.h
  src/software/ai/hl/stp/tactic/chip/chip_fsm_test.cpp
  src/software/ai/hl/stp/tactic/get_behind_ball/get_behind_ball_fsm.cpp
  src/software/ai/hl/stp/tactic/get_behind_ball/get_behind_ball_fsm.h
  src/software/ai/hl/stp/tactic/kick/kick_fsm.cpp
  src/software/ai/hl/stp/tactic/kick/kick_fsm.h
  src/software/ai/hl/stp/tactic/kick/kick_fsm_test.cpp
  src/software/ai/hl/stp/tactic/kick/kick_tactic.h
  src/software/ai/hl/stp/tactic/receiver/receiver_fsm.cpp
  src/software/ai/hl/stp/tactic/receiver/receiver_fsm.h
  src/software/ai/hl/stp/tactic/receiver/receiver_tactic.h
  src/software/ai/hl/stp/tactic/transition_conditions.cpp
  src/software/ai/hl/stp/tactic/transition_conditions.h
  src/software/ai/play_selection_fsm.cpp
Labels: Gameplay, Robocup-2024

#3240 [Gameplay] PassDefenders Should Attempt to Steal Intercepted Balls
  docs/fsm-diagrams.md
  src/proto/parameters.proto
  src/proto/tactic.proto
  src/software/ai/hl/stp/play/defense/defense_play_base.cpp
  src/software/ai/hl/stp/play/defense/defense_play_base.h
  src/software/ai/hl/stp/play/defense/defense_play_fsm.cpp
  src/software/ai/hl/stp/play/enemy_free_kick/enemy_free_kick_play_fsm.cpp
  src/software/ai/hl/stp/tactic/crease_defender/BUILD
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_fsm.cpp
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_fsm.h
  src/software/ai/hl/stp/tactic/defender/BUILD
  src/software/ai/hl/stp/tactic/defender/defender_fsm_base.cpp
  src/software/ai/hl/stp/tactic/defender/defender_fsm_base.h
  src/software/ai/hl/stp/tactic/pass_defender/BUILD
  src/software/ai/hl/stp/tactic/pass_defender/pass_defender_fsm.cpp
  src/software/ai/hl/stp/tactic/pass_defender/pass_defender_fsm.h
  src/software/ai/hl/stp/tactic/pass_defender/pass_defender_fsm_test.cpp
  src/software/ai/hl/stp/tactic/pass_defender/pass_defender_tactic.cpp
  src/software/ai/hl/stp/tactic/pass_defender/pass_defender_tactic.h
  src/software/ai/hl/stp/tactic/pass_defender/pass_defender_tactic_test.py
  src/software/ai/hl/stp/tactic/tactic_factory.cpp
  src/software/ai/motion_constraint/motion_constraint_set_builder_test.cpp
Labels: Robocup-2024

#3254 Avoid Crease Defender Clumping
  src/proto/parameters.proto
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_fsm.cpp
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_fsm.h
  src/software/ai/hl/stp/tactic/crease_defender/crease_defender_fsm_test.cpp
  src/software/ai/motion_constraint/motion_constraint_visitor.cpp
  src/software/geom/algorithms/step_along_perimeter.cpp
  src/software/geom/algorithms/step_along_perimeter_test.cpp
  src/software/geom/polygon.cpp
  src/software/geom/polygon.h
  src/software/geom/polygon_test.cpp
Labels: Robocup-2024
